name: Go Lint

on:
  pull_request:
    paths:
      - "server/**"
  push:
    branches:
      - "main"
    paths:
      - "server/**"

env:
  GOLANGCI_LINT_VERSION: v1.60

jobs:
  react-lint:
    name: React linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: client

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true

  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT
        working-directory: server

  golangci-lint:
    needs: detect-modules
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.23", "stable"]
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint Go v${{ matrix.go-version }}
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.modules }}
