name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: React tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
        working-directory: client

      - run: npm run test
        working-directory: client

      - name: Update JSON
        # if: failure()
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          NODE_VERSION="${{ matrix.node-version }}"
          jq --arg url "$RUN_URL" --arg version "$NODE_VERSION" '.content = "There has been an unexpected deployment error running React tests with Node.js version: \($version)" | .embeds[0].url = $url' .github/assets/alert.json > .github/assets/alert.json

      - name: Discord Webhook Action
        # if: failure()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: .github/assets/alert.json

      - name: Success Notification
        if: success()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Tests passed successfully on Node.js ${{ matrix.node-version }} 🎉"
