name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
        working-directory: client

      - run: npm run test
        working-directory: client

  discord-alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set GitHub run URL
        run: echo "RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - run: |
          echo "🚨 Test failed! View the details here: $RUN_URL"

      - name: Update JSON
        run: |
          jq --arg url "$RUN_URL" '.embeds[0].url = $url' .github/assets/alert.json > tmp.json && mv tmp.json ${{ github.run_id }}.json

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: ${{ github.run_id }}.json
